version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env # Isto vai garantir que as variáveis de ambiente sejam lidas do .env
    depends_on:
      - mysql
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Utiliza a variável do .env
      MYSQL_DATABASE: API
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
    restart: always
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
